[keyboard]
bindings = [{ action = "SpawnNewInstance", key = "N", mods = "Control" }]

[scrolling]
history = 100000
multiplier = 3

[window]
dynamic_title = false
opacity = 1
padding.x = 5
padding.y = 5
dimensions.columns = 130
dimensions.lines = 40

[colors]
draw_bold_text_with_bright_colors = false
